### ISSUE TITLE
Drop CI for Julia Nightly

### ISSUE THREAD

**Issue by oxinabox** [JuliaDiff/FiniteDifferences.jl#135]
we need to drop Julia-Nightly from the CI (out of scope for this PR)

_Originally posted by @oxinabox in https://github.com/JuliaDiff/FiniteDifferences.jl/issues/130#issuecomment-756885741_

allow failures doesn't work on GHA

**Comment by sethaxen** [comment]
Why do we need to drop it? Nightlies are run in a separate workflow from CI precisely so that failing status on nightlies does not produce a failing status for CI. It will show ❌  on all commits whenever nightly is failing, but that's also true for random codecov issues and the like. At the bottom of each PR or whenever one clicks on the ❌ , nightlies are separated from the rest of the CI.

**Comment by oxinabox** [comment]
I guess we don't.
I worry it is boy who cried wolf.
One day I will ignore the wrong cross
