### ISSUE TITLE
How do I choose method order to avoid NaN?

### ISSUE THREAD

**Issue by jessebett** [JuliaDiff/FiniteDifferences.jl#32]
I am running into a situation where choosing specific orders for the Method is causing `NaN`s. Is this expected behaviour (e.g. resulting from some unfortunate math) or is this a bug?

In this example I am trying to take `n`th order directional derivatives. While silly, I've evaluated the `0`th order fdm, and on alternating method orders I'm getting `NaN`s:

```
@test sin(2.) ≈ central_fdm(1,0)(ϵ -> sin(2. +ϵ*1),0.) # Nan
@test sin(2.) ≈ central_fdm(2,0)(ϵ -> sin(2. +ϵ*1),0.) # true
@test sin(2.) ≈ central_fdm(3,0)(ϵ -> sin(2. +ϵ*1),0.) # Nan
@test sin(2.) ≈ central_fdm(4,0)(ϵ -> sin(2. +ϵ*1),0.) # true

@test cos(2.) ≈ central_fdm(2,1)(ϵ -> sin(2. +ϵ*1),0.) # true
@test cos(2.) ≈ central_fdm(3,1)(ϵ -> sin(2. +ϵ*1),0.) # true
@test cos(2.) ≈ central_fdm(4,1)(ϵ -> sin(2. +ϵ*1),0.) # true
@test cos(2.) ≈ central_fdm(5,1)(ϵ -> sin(2. +ϵ*1),0.) # true

@test -sin(2.) ≈ central_fdm(3,2)(ϵ -> sin(2. +ϵ*1),0.) # false but ok
@test -sin(2.) ≈ central_fdm(4,2)(ϵ -> sin(2. +ϵ*1),0.) # true
@test -sin(2.) ≈ central_fdm(5,2)(ϵ -> sin(2. +ϵ*1),0.) # true
@test -sin(2.) ≈ central_fdm(6,2)(ϵ -> sin(2. +ϵ*1),0.) # true
```

Note that I'm only observing this on the 0th order `fdm`.

**Comment by willtebbutt** [comment]
@wesselb anything obvious here?

**Comment by wesselb** [comment]
Ah, nice find! This is an edge case that should be checked for.

The minimum of the upper bound on the error to find the step size fails for odd order, because in that case `C_2` ([here](https://github.com/JuliaDiff/FiniteDifferences.jl/blob/master/src/methods.jl#L251)) is zero. If you're combining `f(x - h)`, `f(x)`, and `f(x + h)` (order 3) to find `f(x)`,  you'd give them coefficients `0`, `1` and `0` respectively, in which case `C_2` is zero. If, however, you're combining `f(x - h)` and `f(x + h)` (order 2), you'd use `0.5` and `0.5`, in which case `C_2` is not zero.

**Comment by willtebbutt** [comment]
Thanks for the info @wesselb. Do you have time to make the necessary PR at some point?
